[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
verbosity = 1

[fuzz]
runs = 1000
max_test_rejects = 100000
seed = "0x1234"

[invariant]
runs = 256
depth = 150
fail_on_revert = false
show_metrics = true