[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
verbosity = 3

[profile.fuzz]
runs = 500
max_test_rejects = 100000
seed = "0x1234"

[profile.invariant]
runs = 100
depth = 200
fail_on_revert = false
call_delay = 0
dictionary_weight = 50
include_storage = true
include_push_bytes = true
show_stats = true
show_calldata = true
# Show additional metrics
shrink_sequence = true